site_title: DDMM Help

navigation:
  -
    name: Welcome
    links:
      -
        title: Home
        link: /
  - name: User Guide
    links:
      -
        title: Download and Setup
        link: /user-guide/setup
  - name: Links
    links:
      -
        title: Main Site
        link: https://doki.space
      -
        title: Discord
        link: https://doki.space/discord