site_title: DDMM Help

navigation:
  -
    name: Welcome
    links:
      -
        title: Home
        link: /
  - name: User Guide
    links:
      -
        title: Download and Setup
        link: /user-guide/setup