site_title: DDMM Help

navigation:
  - name: Welcome
    links:
      - title: Home
        link: /
  - name: User Guide
    links:
      - title: Download and Setup
        link: /user-guide/setup.html
      - title: Installing DDLC
        link: /user-guide/install-ddlc.html
  - name: API Tutorial
    links:
      - title: Mod Metadata
        link: /api-tutorial/mod-metadata.html
  - name: Links
    links:
      - title: Main Site
        link: https://doki.space
      - title: Discord
        link: https://doki.space/discord