site_title: DDMM Help

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

navigation:
  - name: Welcome
    links:
      - title: Home
        link: /
  - name: User Guide
    links:
      - title: Download and Setup
        link: /user-guide/setup.html
      - title: Installing DDLC
        link: /user-guide/install-ddlc.html
  - name: API Tutorial
    links:
      - title: Mod Metadata
        link: /api-tutorial/mod-metadata.html
      - title: Achievements with the SDK
        link: /api-tutorial/achievements-with-sdk.html
  - name: Links
    links:
      - title: Main Site
        link: https://doki.space
      - title: Discord
        link: https://doki.space/discord
